
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-default}
      GMAIL_ADRESS: ${GMAIL_ADRESS:-default}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD:-default}
      DATABASE_URL: ${DATABASE_URL:-default}